// Canonical policy copy. Rendered as real pages at /privacy, /about, /tos,
// /copyright and /contact, and reused by the in-page view in the gallery.
// Single source of truth: edit here, both places follow.
export const POLICIES = {
  privacy: "<h1>Privacy Policy</h1>"
    + "<p class='updated'>Last updated: 7 October 2026</p>"
    + "<p class='lead'>This policy explains what 8K Wallpapers collects, why, and what control you have over it. If anything here is unclear, email us at <a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a> and we will answer.</p>"
    + "<h3>The short version</h3>"
    + "<p>You can browse and download every wallpaper without an account and without telling us who you are. We do not sell personal information. The data we do hold exists to run the site, credit contributors, and answer copyright complaints.</p>"
    + "<h3>Information we collect</h3>"
    + "<ul><li><b>Server logs.</b> Like any website, our host records the IP address, browser type, referring page, and time of each request. These logs are used to keep the site running and to investigate abuse.</li>"
    + "<li><b>Stored on your device.</b> Your saved wallpapers, your light or dark theme choice, your advertising consent choice, and a record of which wallpapers you have already viewed or voted on are kept in your browser's local storage. They never leave your device, and clearing your browser data removes them.</li>"
    + "<li><b>If you sign in with Google.</b> We receive a stable account identifier, your email address, display name, and profile picture. We never receive your Google password.</li>"
    + "<li><b>If you submit a wallpaper or file a report.</b> We keep what you enter, plus a one-way salted hash of your IP address. The hash lets us enforce rate limits and our repeat-infringer policy without storing the address itself.</li></ul>"
    + "<h3>Cookies and similar technologies</h3>"
    + "<p>A cookie is a small file a site stores in your browser. We use one for your sign-in session, which is removed when you sign out. Google Analytics and our advertising partners may set their own, as described below. You can block or delete cookies in your browser settings; the gallery keeps working if you do, though you will be signed out.</p>"
    + "<h3>Advertising</h3>"
    + "<p>This site is supported by advertising served through Google AdSense.</p>"
    + "<ul><li>Third-party vendors, including Google, use cookies to serve ads based on your prior visits to this website or other websites.</li>"
    + "<li>Google's use of advertising cookies enables it and its partners to serve ads to you based on your visit to this site and/or other sites on the internet.</li>"
    + "<li>You may opt out of personalised advertising by visiting <a href='https://www.google.com/settings/ads' target='_blank' rel='noopener nofollow'>Google Ads Settings</a>.</li>"
    + "<li>You can opt out of a third-party vendor's use of cookies for personalised advertising at <a href='https://www.aboutads.info/choices/' target='_blank' rel='noopener nofollow'>aboutads.info/choices</a>.</li>"
    + "<li>How Google uses data from sites that use its services is described at <a href='https://policies.google.com/technologies/partner-sites' target='_blank' rel='noopener nofollow'>policies.google.com/technologies/partner-sites</a>.</li></ul>"
    + "<p>We also use the Reddit Pixel to measure our own advertising on Reddit. When you visit this site, Reddit may record the visit using cookies and similar technologies, so we can see how many visitors arrive from our Reddit ads. We do not send Reddit your name, email address or other contact details. Reddit handles this data under its <a href='https://www.reddit.com/policies/privacy-policy' target='_blank' rel='noopener nofollow'>privacy policy</a>, and if you have a Reddit account you can stop Reddit using activity from other sites to personalise your ads in your <a href='https://www.reddit.com/settings/privacy' target='_blank' rel='noopener nofollow'>Reddit privacy settings</a>.</p><p>Visitors in the European Economic Area, the United Kingdom and Switzerland are asked for consent before any advertising cookies are set. Declining is honoured, remembered on your device, and the site remains fully usable. You can change your answer by clearing this site's data in your browser.</p>"
    + "<p>We have no access to or control over cookies set by advertisers. Consult their privacy policies for details of their practices.</p>"
    + "<h3>Analytics</h3>"
    + "<p>We use Google Tag Manager to load Google Analytics, which measures how the site is used: pages viewed, how visitors arrived, approximate location (country or city), and device and browser type. It uses cookies and similar identifiers to do this. We use the results to see which wallpapers and pages are popular and to improve the site, not to identify you. Google processes this data under its <a href='https://policies.google.com/privacy' target='_blank' rel='noopener nofollow'>privacy policy</a>; see also <a href='https://policies.google.com/technologies/partner-sites' target='_blank' rel='noopener nofollow'>how Google uses information from sites that use its services</a>.</p><p>For visitors in the European Economic Area, the United Kingdom and Switzerland, analytics and advertising cookies are off by default (Google Consent Mode). Without your agreement Google receives only cookieless measurements that do not identify your browser. Anyone can opt out of Google Analytics with Google's <a href='https://tools.google.com/dlpage/gaoptout' target='_blank' rel='noopener nofollow'>browser add-on</a>.</p><p>The view, like and download counts shown on wallpapers are our own, are counted once per browser, and are not tied to an identity.</p>"
    + "<h3>Children</h3>"
    + "<p>This site is not directed at children under 13, and we do not knowingly collect information from them. If you believe a child has given us personal information, email us and we will delete it.</p>"
    + "<h3>Your rights</h3>"
    + "<p>You can ask us what we hold about you, ask for it to be corrected, or ask for your account and its data to be deleted &mdash; email <a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a> and we will action it within 30 days. Depending on where you live, these rights may be guaranteed by Canada's PIPEDA, the GDPR, or the CCPA. We do not sell personal information, so there is nothing to opt out of under the CCPA's \"do not sell\" provision.</p>"
    + "<h3>Retention</h3>"
    + "<p>Account records are kept while the account exists. Submission and report records are kept for as long as needed to operate the repeat-infringer policy and to answer any legal claim about them. Server logs are kept only briefly by our host.</p>"
    + "<h3>Where your data is handled</h3>"
    + "<p>This site is operated from Canada and hosted on Cloudflare's global network, so requests are served from, and data may be processed in, the country closest to you.</p>"
    + "<h3>Changes</h3>"
    + "<p>If this policy changes materially we will update the date at the top of this page.</p>"
    + "<p>Questions: <a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a></p>",
  tos: "<h1>Terms of Service</h1>"
    + "<p class='updated'>Last updated: 31 July 2026</p>"
    + "<p class='lead'>By using 8K Wallpapers you agree to what follows. If you do not agree, please do not use the site.</p>"
    + "<h3>Using the wallpapers</h3>"
    + "<p>Wallpapers here are free to download and use as a background on your own devices, personal or work. You may not resell them, redistribute them as your own collection, bundle them into an app or product, or claim authorship of them. Some images carry the licence of the photographer or platform they came from; where a source is credited, that licence governs.</p>"
    + "<h3>Submitting a wallpaper</h3>"
    + "<p>You may only submit images you created or otherwise hold the rights to share. By submitting you confirm you have those rights and grant us a non-exclusive, royalty-free licence to host, resize and display the image on this site, and to remove it at any time. You keep ownership of your work. Every submission is reviewed by a person before it appears.</p>"
    + "<h3>Acceptable use</h3>"
    + "<p>Do not upload material that infringes copyright; that is sexual, violent or hateful; that shows a real person who has not agreed to it; or that is unlawful. Do not scrape the library in bulk, attempt to overload the service, or interfere with its security. We may refuse, remove or block anything at our discretion.</p>"
    + "<h3>Accounts</h3>"
    + "<p>Accounts are optional and exist so contributors can be credited. You are responsible for the Google account you sign in with. We may suspend an account that breaks these terms, in particular one associated with repeated copyright notices, as set out in the Copyright policy.</p>"
    + "<h3>Advertising</h3>"
    + "<p>The site is supported by advertising. We do not control which ads are shown and do not endorse advertisers or anything they link to. Dealings with an advertiser are between you and them.</p>"
    + "<h3>Availability</h3>"
    + "<p>The site is provided as-is and as-available. We do not promise it will be uninterrupted or error-free, and we may change or withdraw any part of it. To the fullest extent the law allows, we are not liable for indirect or consequential loss arising from your use of the site.</p>"
    + "<h3>Reporting a problem</h3>"
    + "<p>Use the <a href='/report'>Report Image</a> page for anything wrong with an image, or email <a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a> for anything else. Copyright complaints follow the process in our Copyright policy.</p>"
    + "<h3>Changes and governing law</h3>"
    + "<p>We may update these terms; the date at the top shows when they last changed, and continuing to use the site means you accept the current version. These terms are governed by the laws of Canada, without regard to conflict-of-law rules.</p>"
    + "<p>Questions: <a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a></p>",
  copyright: "<h1>Copyright Policy</h1>"
    + "<p class='updated'>Last updated: 31 July 2026</p>"
    + "<p class='lead'>This is a community-supported website with the majority of published content being uploaded by our user community or collected from a wide range of free image resources.</p>"
    + "<p>Although published content is believed to be authorized for sharing and personal use as desktop wallpaper &mdash; either by the uploader or author, or by being public-domain or freely licensed &mdash; unless otherwise noted in the wallpaper description, all images on this website are copyrighted by their respective authors. If you wish to use these images for any other purpose, you must get permission from their respective authors.</p>"
    + "<p>If you object to a wallpaper published on our site, please contact us with the wallpaper title or URL and your reason for concern &mdash; whether it is your own work that you do not wish to share, or something you find explicit, unethical, or inappropriate.</p>"
    + "<p>We reserve the right to decide whether or not to host any wallpaper that was submitted by users.</p>"
    + "<p>We are an online service provider as defined in the Digital Millennium Copyright Act. We provide legal copyright owners with the ability to self-publish on the internet by uploading, storing, and displaying various media utilizing our services.</p>"
    + "<p class='emph'>We have no intention of violating anyone's copyright, and take the matter very seriously. If you are a copyright holder of a particular image, please report it using \"Report Image.\"</p>"
    + "<h3>Filing a Takedown Notice</h3>"
    + "<p>To report material you believe infringes your copyright, send a notice to our designated agent including: your contact details; identification of the work you say is infringed; the URL of the material in question; a statement that you have a good-faith belief the use is not authorised; a statement, under penalty of perjury, that the information is accurate and that you are the owner or authorised to act for them; and your signature.</p>"
    + "<div class='contact-card'>"
    + "<div class='row'><b>Agent</b><span>Kiir Achuk, 8K Wallpapers</span></div>"
    + "<div class='row'><b>Address</b><span>161 Buckmasters Circle, St. John&rsquo;s, NL A1C 4V7, Canada</span></div>"
    + "<div class='row'><b>Phone</b><span>+1 709-219-1793</span></div>"
    + "<div class='row'><b>Email</b><span><a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a></span></div>"
    + "<div class='row'><b>Response</b><span>Valid notices are actioned promptly, usually within 1&ndash;2 business days.</span></div>"
    + "</div>"
    + "<p style='font-size:13px;color:var(--muted)'>This agent is registered with the U.S. Copyright Office in the DMCA Designated Agent Directory (registered 16 August 2026). The registration is renewed every three years, as the law requires.</p>"
    + "<h3>Notice and Notice (Canada)</h3>"
    + "<p>This site is operated from Canada, where the <i>Copyright Act</i> establishes a &ldquo;notice and notice&rdquo; regime rather than notice and takedown. When we receive a valid notice of claimed infringement about user-submitted material, we forward that notice to the person who submitted it and retain the records identifying them for the period required by law. We are not obliged under Canadian law to remove the material on notice alone.</p>"
    + "<p>In practice we go further than the minimum: because this site reviews submissions before publication and serves a largely international audience, we also remove material promptly in response to a well-founded notice, and we operate the designated-agent process described above so that rights holders in the United States can reach us through the channel they expect.</p>"
    + "<h3>Repeat Infringers</h3>"
    + "<p>We keep a record of submissions that are the subject of valid takedown notices and block submitters associated with repeated notices, as described in our Terms of Service.</p>"
    + "<p style='font-size:13px;color:var(--muted)'>This page describes our practice, not legal advice, and is not a substitute for advice from a qualified lawyer in your jurisdiction.</p>"
    + "<p style='font-size:13px;color:var(--muted)'>Wallpapers here come from a mix of sources: images created for this site, and images submitted by visitors, each reviewed by hand before publishing. This policy describes our practice and is not legal advice.</p>",

  contact: "<h1>Contact Us</h1>"
    + "<p class='updated'>Last updated: 31 July 2026</p>"
    + "<p class='lead'>8K Wallpapers is run by one person in Canada. Every message goes to a real inbox and gets a real reply &mdash; there is no ticket robot here.</p>"
    + "<div class='contact-card'>"
    + "<div class='row'><b>Email</b><span><a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a></span></div>"
    + "<div class='row'><b>Response</b><span>Usually within 2&ndash;3 business days.</span></div>"
    + "<div class='row'><b>Based in</b><span>Canada &mdash; replies are sent in English.</span></div>"
    + "</div>"
    + "<h3>Something wrong with an image</h3>"
    + "<p>Use the <a href='/report'>Report Image</a> page rather than email. It attaches the exact wallpaper, gives you a reference number, and those reports are read first. Copyright claims filed there follow the process in our Copyright policy.</p>"
    + "<h3>Requests and corrections</h3>"
    + "<p>Want a wallpaper in a size that is not listed, spotted a wrong credit, or found a broken download? Email us with the wallpaper name and we will fix it.</p>"
    + "<h3>Contributing</h3>"
    + "<p>You can <a href='/upload'>submit a wallpaper</a> directly. Every submission is reviewed by hand, and you are credited by name if you ask to be.</p>"
    + "<h3>Advertising and business enquiries</h3>"
    + "<p>Email the address above with \"advertising\" in the subject line.</p>",
  about: "<h1>About</h1>"
    + "<p class='lead'>8K Wallpapers is a hand-curated gallery of ultra-high-definition backgrounds, free to download for personal use on desktop, phone and tablet.</p>"
    + "<h3>What this site is</h3>"
    + "<p>It is a small independent project, run from Canada by one person, built because finding a genuinely high-resolution wallpaper that fits your screen is more annoying than it should be. There is no sign-up wall and no download counter forcing you to wait &mdash; you pick a size and the file is yours.</p>"
    + "<h3>What you will find</h3>"
    + "<ul><li>Wallpapers up to 8K (7680&times;4320), organised by category and tag.</li>"
    + "<li>A download sized to the screen you are actually using, alongside Full HD, ultrawide and phone presets.</li>"
    + "<li>Most viewed, most liked and most downloaded rows built from real counts, not invented numbers.</li>"
    + "<li>Favourites you can save without an account.</li></ul>"
    + "<h3>Where the images come from</h3>"
    + "<p>Some are generated or created for this site. Others are submitted by visitors, who are credited by name where they ask to be. Every submission is reviewed by a person before it goes live, and anything credited to an outside photographer or platform keeps that credit and its licence.</p>"
    + "<h3>Reporting something</h3>"
    + "<p>If an image is yours and should not be here, or there is something wrong with it, the <a href='/report'>Report Image</a> page reaches a person and is answered first. Copyright claims are handled under our Copyright policy.</p>"
    + "<h3>Contact</h3>"
    + "<p>Email <a href='mailto:8kwallpapersupport@gmail.com'>8kwallpapersupport@gmail.com</a> &mdash; questions, requests and corrections are all welcome. We usually reply within 2&ndash;3 business days.</p>"
};
